services:
  app:
    image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/${REPOSITORY_NAME}:${TAG}
    ports:
      - "8000:8000"
    environment:
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    env_file:
      - .env
